# Generated by Django 2.1.7 on 2019-03-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establishments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('address', models.CharField(max_length=128)),
                ('zipCode', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('establishment', models.ForeignKey(on_delete=None, to='UBeer.Establishments')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('date', models.DateTimeField()),
                ('establishment', models.ForeignKey(on_delete=None, to='UBeer.Establishments')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionsMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuID', models.ForeignKey(on_delete=None, to='UBeer.Menu')),
                ('transaction', models.ForeignKey(on_delete=None, to='UBeer.Transactions')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('R', 'Rider'), ('E', 'Establishment')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(on_delete=None, to='UBeer.Users'),
        ),
        migrations.AddField(
            model_name='establishments',
            name='user',
            field=models.ForeignKey(on_delete=None, to='UBeer.Users'),
        ),
    ]
