# Generated by Django 2.1.7 on 2019-04-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UBeer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishments',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='establishments',
            name='longitude',
        ),
        migrations.AddField(
            model_name='establishments',
            name='image',
            field=models.ImageField(default='/static/images/establishment_icon.png', upload_to='media/gallery'),
        ),
        migrations.AddField(
            model_name='establishments',
            name='info',
            field=models.CharField(default='{INFO}', max_length=255),
        ),
        migrations.AddField(
            model_name='establishments',
            name='name',
            field=models.CharField(default='{NAME}', max_length=255),
        ),
        migrations.AddField(
            model_name='establishments',
            name='rating',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='establishments',
            name='ride_time',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='establishments',
            name='minimum_tab',
            field=models.IntegerField(default=-1),
        ),
    ]
